name: FantasyProtection
version: 2.0
author: Enrick3344
main: FantasyProtection\Main
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]

permission:
    fantasyprotection.break.bypass:
        default: op
    fantasyprotection.place.bypass:
        default: op
    fantasyprotection.drop.bypass:
        default: op
    fantasyprotection.command.protection:
        default: op
    fantasyprotection.close.bypass:
        default: false
